apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: capi-quickstart
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Breee/argocd-issue-11972
    targetRevision: HEAD
    path: capi-quickstart-chart
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
